### ISSUE TITLE
Error importing osv in Python 3.9

### ISSUE THREAD

**Issue by javihernandez** [google/osv.dev#2281]
**Describe the bug**
Since last 0.0.21 update, on Python 3.9, I can no longer make use of `osv` as I get the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/code/alws/utils/osv.py", line 5, in <module>
    from errata2osv import errata_to_osv
  File "/usr/local/lib/python3.9/site-packages/errata2osv.py", line 6, in <module>
    from src.models import *
  File "/usr/local/lib/python3.9/site-packages/src/models/__init__.py", line 1, in <module>
    from .converter import *
  File "/usr/local/lib/python3.9/site-packages/src/models/converter.py", line 4, in <module>
    from osv import Bug
  File "/usr/local/lib/python3.9/site-packages/osv/__init__.py", line 17, in <module>
    from .impact import *
  File "/usr/local/lib/python3.9/site-packages/osv/impact.py", line 31, in <module>
    from . import models
  File "/usr/local/lib/python3.9/site-packages/osv/models.py", line 31, in <module>
    from . import purl_helpers
  File "/usr/local/lib/python3.9/site-packages/osv/purl_helpers.py", line 42, in <module>
    def package_to_purl(ecosystem: str, package_name: str) -> str | None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a python 3.9 env
2. Install osv through any installation method
3. Try importing `purl_helpers`
**Expected behaviour**
I expect `purl_helpers` to be loaded without any problem

**Additional context**
If not wrong, type annotations like ` str | None` support was introduced in 3.10, and I see that, according to osv docs, it's supposed to work in `Python >= 3.7`.

**Comment by hogo6002** [comment]
Yeah, we will drop support and require `Python >= 3.10`. I will update docs to reflect this. Thanks for reporting it!
