### ISSUE TITLE
Debian version exception

### ISSUE THREAD

**Issue by oliverchang** [google/osv.dev#564]
```
 File "/usr/local/bin/worker.py", line 531, in _do_process_task
    self._source_update(message)
  File "/usr/local/bin/worker.py", line 381, in _source_update
    self._do_update(source_repo, repo, vulnerability, path, original_sha256)
  File "/usr/local/bin/worker.py", line 458, in _do_update
    result = self._analyze_vulnerability(source_repo, repo, vulnerability,
  File "/usr/local/bin/worker.py", line 426, in _analyze_vulnerability
    result = osv.analyze(
  File "/env/osv/impact.py", line 492, in analyze
    enumerate_versions(affected_package.package.name,
  File "/env/osv/impact.py", line 400, in enumerate_versions
    current_versions = ecosystem.enumerate_versions(
  File "/env/osv/ecosystems.py", line 353, in enumerate_versions
    versions.sort(key=self.sort_key)
  File "/env/osv/ecosystems.py", line 336, in sort_key
    return DebianVersion.from_string(version)
  File "/env/osv/third_party/univers/debian.py", line 141, in from_string
    raise ValueError('Invalid version string: "{}"'.format(version))
ValueError: Invalid version string: "1:Beta2-2.1"
```

**Comment by oliverchang** [comment]
Another one:

```
"Unexpected exception while processing task: Traceback (most recent call last):
  File "/usr/local/bin/worker.py", line 535, in _do_process_task
    self._source_update(message)
  File "/usr/local/bin/worker.py", line 385, in _source_update
    self._do_update(source_repo, repo, vulnerability, path, original_sha256)
  File "/usr/local/bin/worker.py", line 462, in _do_update
    result = self._analyze_vulnerability(source_repo, repo, vulnerability,
  File "/usr/local/bin/worker.py", line 430, in _analyze_vulnerability
    result = osv.analyze(
  File "/env/osv/impact.py", line 492, in analyze
    enumerate_versions(affected_package.package.name,
  File "/env/osv/impact.py", line 390, in enumerate_versions
    sorted_events.sort(key=sort_key)
  File "/env/osv/impact.py", line 388, in sort_key
    return ecosystem.sort_key(event.fixed)
  File "/env/osv/ecosystems.py", line 337, in sort_key
    return DebianVersion.from_string(version)
  File "/env/osv/third_party/univers/debian.py", line 141, in from_string
    raise ValueError('Invalid version string: "{}"'.format(version))
ValueError: Invalid version string: "<end-of-life>"
```
