### ISSUE TITLE
OSS-Fuzz fixes not getting added back to oss-fuzz-vulns

### ISSUE THREAD

**Issue by oliverchang** [google/osv.dev#963]
e.g. https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=49613 was verified, but https://github.com/google/oss-fuzz-vulns/blob/36a68e60615c1b3bb1be3b5d16fab36bd819cffc/vulns/libredwg/OSV-2022-657.yaml does not have the fix info.

**Comment by oliverchang** [comment]
Another example: https://github.com/google/oss-fuzz-vulns/blob/main/vulns/spirv-tools/OSV-2022-1119.yaml

**Comment by oliverchang** [comment]
Cause:

```
message: "Bisect failed with unexpected exception:
Traceback (most recent call last):
  File "/usr/local/bin/oss_fuzz.py", line 129, in do_bisect
    result = bisector.bisect(bisect_type, old_commit, new_commit, f.name,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/oss-fuzz/infra/bisector.py", line 306, in bisect
    return _bisect(bisect_type, old_commit, new_commit, testcase_path,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/oss-fuzz/infra/bisector.py", line 220, in _bisect
    expected_error = _check_for_crash(build_data.project_name, fuzz_target,
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/oss-fuzz/infra/bisector.py", line 148, in _check_for_crash
    out, err, return_code = helper.reproduce_impl(
                            ^^^^^^^^^^^^^^^^^^^^^^
  File "/work/oss-fuzz/infra/helper.py", line 1221, in reproduce_impl
    return run_function(run_args, architecture=architecture)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: _check_for_crash.<locals>.docker_run() got an unexpected keyword argument 'architecture'
"
source_id: "oss-fuzz:6273056472956928"
```

(We should've noticed this earlier)

**Comment by oliverchang** [comment]
Exception has been fixed upstream in OSS-Fuzz. Kicking off a re-analysis of all the affected OSS-Fuzz vulns (since December 2022).

**Comment by oliverchang** [comment]
This should be fixed now. e.g. https://github.com/google/oss-fuzz-vulns/blob/main/vulns/libredwg/OSV-2022-657.yaml now has the correct fix commit.
